Completed react-accordion exercise - Shea
SheaPone/m2-1224-code-solutions pull request #16
Opened 2024-12-20 05:26 UTC by SheaPone

https://github.com/user-attachments/assets/5a55b9d2-10c9-4aa5-a26e-0247ba154990

2025-01-03 03:15 UTC, gerardoh13 commented on react-accordion/my-app/src/Accordion.tsx
> +        <div>
When we map through arrays to render in React the key needs to be on the outermost element. 
You can either remove the div wrapping the TopicCard or put the key as a property of the div instead of the TopicCard.

2025-01-03 03:17 UTC, gerardoh13 commented on react-accordion/my-app/src/TopicCard.tsx
> +    <section className="card" onClick={onShow} onDoubleClick={onDoubleClick}>
To avoid the TopicCard from resizing when it is opened you can give it a width. eg. width: "700px". You can either do it inline, or use the "card" className you already gave the card.

2025-01-03 03:20 UTC, gerardoh13 requested changes
Fix the issue with the key when you map the TopicCards so that there aren't errors on your console when it renders. 
The css on the TopicCard is optional, but it will make it look nicer.

2025-01-07 02:02 UTC, SheaPone commented
<img width="406" alt="Screenshot 2025-01-06 at 6 00 45 PM" src="https://github.com/user-attachments/assets/bf0f902b-1049-4c53-b749-d0e0fc19da8b" />

2025-01-07 04:36 UTC, gerardoh13 approved these changes
Looks good!

2025-01-08 02:32 UTC, merged